### ISSUE TITLE
Automate linting

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#132]
It would be nice to automatically lint in our continuous integration pipeline. We can discuss what to use here, but some options include [pycodestyle](https://github.com/PyCQA/pycodestyle), [pylint](https://github.com/PyCQA/pylint), and [flake8](https://github.com/PyCQA/flake8). We could also look into something that automatically formats code like [black](https://github.com/ambv/black).

Let's use this issue to decide what we want to use.

**Comment by lwasser** [comment]
yes please!! you know linting is really difficult to force on people. it might be nice to have something like black running to keep things tidy. i haven't run it yet locally. i hate the function syntax but @betatim  speaks really highly of it. 

i mean do we want to spend time linting or coding is the question :)

**Comment by betatim** [comment]
I like carefully hand crafting the layout of the code so it is just right and follows PEP8 so I was a bit "eeewww, automatic!??!" when I started using black. However after using it for a while and considering how much better uniformly formatted code is and how little I enjoy discussing with others that "no, that isn't pep8" I am liking black more and more as an automatic tool that just runs when you `git commit`. Maybe with the proviso that you set the line length back to 79 because ... I can not get over that :)

**Comment by lwasser** [comment]
yea me too. the one thing i don't like is the function format which is i think:

```
def som_fun(one, var2, 
):
```
That to me looks weird. But maybe i'll get used to it?!

I also think it's silly to spend time formatting code when you can instead just write and fix code and documentation. i'm all for formatting happening on the fly without having to fight with flake8 and pylint on travis. @betatim can you direct us to a package that implements black on a commit so we can see how that would happen?

**Comment by betatim** [comment]
I'll have a look how to do that. I know https://github.com/nteract/nteract/ runs some kind of formatter on checkin (but it is JS so they don't use black). I'll post here when I find out.

**Comment by mbjoseph** [comment]
Here is a tutorial that describes using pre-commit hooks with black and flake8: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
