### ISSUE TITLE
Normalized diff function - What order would a user expect the bands to be in?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#2]
Currently we have  a `normalized_diff()` function which calculated norm diff of 2 bands. 
It's nice and generic in that it can be used on ANY raster data BUT question

1. is the band order what a user would expect? i think it's the OPPOSITE of what i taught in my R class. 
2. the name could be shorter. SHould i rename it to `norm_diff()` ? 

hey @mbjoseph @joemcglinchy @jlpalomino have a look at the function and see what you think. I won't change it during the semester but am open to changing it in December if you guys think it should be the opposite? Or is it ok?

**Comment by joemcglinchy** [comment]
https://github.com/earthlab/earthpy/blob/9a4fc7cd765152b727a8d59834623d72f0ac9d1e/earthpy/spatial.py#L43

I think the doc is perfect, but the order of the arguments should be reversed. I think this is more intuitive since b2 comes first in the numerator and denominator for the normalized difference equation.

**Comment by mbjoseph** [comment]
I wouldn't have any strong prior expectations for the ordering of bands for a function like this.

**Comment by joemcglinchy** [comment]
it is more subjective... as long as the doc is clear on which bands go where in the equation, which I think it is. seeing the equation (b2 - b1) / (b2 + b1), implies to me, that the the args should come in as b2 and then b1, but that's a little weird since it sounds like you're counting backwards and we read left to right.

**Comment by lwasser** [comment]
just a note all that in line with @joemcglinchy 's original thought and @jlpalomino 's second.... that the order of bands in the norm_diff function is confusing... several students have voiced the same issue! This is why i originally created this issue. @joemcglinchy i know you made some changes... Do you want to resubmit the PR to adjust the function and also update the docs, [here](https://github.com/earthlab/earthpy/blob/master/docs/spatial-raster.rst) and we can then decide when to merge it the students have an assignment where they will likely use it starting today. but after thanksgiving could be a good time to merge this. then we'd want to update our lessons too. not a big deal to do tho!

**Comment by lwasser** [comment]
@jlpalomino  assigning this issue to you when you add tests for norm_diff please also just swap the parameter order!

**Comment by lwasser** [comment]
referencing this pr which has the changes implemented.  - https://github.com/earthlab/earthpy/pull/140

@jlpalomino will you please also close this issue when the PR is merged!
