### ISSUE TITLE
code cov?? whahhhhhhtttttt?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#24]
@mbjoseph can you tell me what code cov is testing for? pretty please. i haz needz clarificationzzzz.

**Comment by mbjoseph** [comment]
Codecov is measure the coverage of the unit tests, e.g., what fraction of code is executed in the process of running the tests (more here: https://en.wikipedia.org/wiki/Code_coverage). Currently  coverage is very low, since we're not actually hitting any of the meaningful code in the package (e.g., the code inside of our class and function definitions).

**Comment by mbjoseph** [comment]
@lwasser there is some coverage because we import earthpy in the unit tests. To see what lines are being run you can go here: https://codecov.io/gh/earthlab/earthpy/tree/master/earthpy

So, we are running all of `__init__.py` and then essentially just defining our functions and methods in the `io.py`, `spatial.py`, and `utils.py`, but if you go to see what lines within those scripts are being run (https://codecov.io/gh/earthlab/earthpy/src/master/earthpy/spatial.py) you can see that the functions are not executed yet - they are only defined.

**Comment by lwasser** [comment]
ok i think i follow now @mbjoseph  i'll close this for the time being because we are about to get a bunch of PR's from students but will reopen if i have more questions!!
