### ISSUE TITLE
We are missing a few tests for _stack_bands

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#240]
I am working on earthpy and noticed that we are missing a few tests for `_stack_bands`.

@joemcglinchy are you willing to tackle a few more tests to fill out the stack functionality?
The missing tests are for the following lines:

- [x] https://codecov.io/gh/earthlab/earthpy/src/master/earthpy/spatial.py#L257
- [ ] https://codecov.io/gh/earthlab/earthpy/src/master/earthpy/spatial.py#L268

The first test should be fairly straightforward. Just send the stack helper a non raster reader object.
It looks like the second just needs a 2 dim array?? i think atleast on first glance. 

Please let me know if you have capacity to work on this.

**Comment by joemcglinchy** [comment]
we can't provide a 2D array to `_stack()`, it expects Dataset Reader objects. So, we can test the `ValueError` with a 2D array for sure. If we can live without L268 of code being covered in the tests, I would suggest doing so. Otherwise we will have to get creative to cover that line. I am happy to submit a PR for testing the ValueError, though!

**Comment by lwasser** [comment]
Ok let’s start there! It seems to me that you could send it a non raster reader object and it should fail gracefully … ie it it would trigger that test that the format is correct?? I’ll have a closer look.

That would be fantastic. I also noticed the stack_raster_tifs() function should be tested just to ensure it returns a warning 😊 that should be rather straight forward as well. Thank you, Joe.

**Comment by lwasser** [comment]
fixed via : https://github.com/earthlab/earthpy/pull/241  thank you @joemcglinchy !!!
