### ISSUE TITLE
Time to update the readme with better install instructions

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#302]
The current readme

* still references the old pip install from github instructions
* doesn't mention conda-forge (yay!)
* is outdated.

Update the readme to present a friendly overview of how to install and use EarthPy

**Comment by mbjoseph** [comment]
@lwasser here's a checklist I stole from https://github.com/noffle/art-of-readme

- [x] One-liner explaining the purpose (A package that makes it easier to plot, and manipulate spatial data in Python.)
- [ ] Necessary background context & links (e.g., we wrote this package because xyz...)
- [ ] Potentially unfamiliar terms link to informative sources
- [x] Installation instructions
- [ ] Clear, runnable example of usage (not sure what this should be, but it should be short and give a sense for what EarthPy does)
- [ ] Performs cognitive funneling (start broad at top, and have detail toward the bottom)
- [ ] Caveats and limitations 
- [ ] Doesn't rely on images to relay critical information
- [ ] License info

Some specific things that we might consider: 

- Link to contributing docs 
- Remove text about testing and making docs (this is now in the contributing docs)
- Move **Data generated for testing** to contributing docs (that content is not yet in the contributing docs)

**Comment by lwasser** [comment]
i think that for the usable examples, we should build out vignettes and link to them directly. i've started this process. then each time we add a vignette we can update the readme!

**Comment by lwasser** [comment]
ok i am closing this given the above merged PR. if there are other readme items that require updates, let's open a shiny new issue!!
