### ISSUE TITLE
Add crop argument to  es.stack() ?? OR update crop_image to support numpy arrays

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#308]
Currently, there are two functions you have to use to stack a raster, and then crop is to the size of a GeoPandas dataframe, `es.stack()` and `es.crop_image()`. There functions both work really well, however, there are some awkward steps between them that could be cleaned up if we implemented a crop argument in `es.stack()`. 

The current workflow can be seen in my rough draft of a stack/crop vignette here: https://github.com/earthlab/earthpy/pull/307. 

The main issue is that `es.crop_image()` only takes a rasterio object. This means that you have to output a raster from the stack, and then assign the output of `rio.open(raster)` to a variable in the script, to later be used in `es.crop_image()`. It is preferable to not assign `rio.open(raster)` to a variable, and instead to use `with rio.open(raster) as object:` and use the rasterio object in that with statement, since if you assign it to a variable you have to remember to close the rasterio object to avoid sloppy data usage. This is impossible to do if you want to use rasterio object outside of the with statement, as you have to do in order to crop the data. If crop was an argument in stack, then this would not be an issue, and could be taken care of within the function.

**Comment by mirob9363** [comment]
Yes, I agree! I am working through the Earth Analytics Python course lessons, and I have found times that the code could be cleaned up a lot if either `crop_image()` could take more than just rasterio objects, or if a crop option was added to `es.stack()`.

**Comment by lwasser** [comment]
ok... lets rope in @joemcglinchy here... 
i just posted on the rasterio discussion forum and one person provided this example

https://github.com/corteva/geocube/blob/582ea0c2f3f0ba91326de098b75412e5033bee21/geocube/xarray_extensions/rioxarray.py#L617

of a way to potentially crop an array without having to read and write another raster object. ideally we would do this instead of making stack() more complicated... but let's talk through it. 

It looks like this is what we want to do
```
width, height = self.shape
clip_mask_arr = geometry_mask(
            geometries=geometries,
            out_shape=(int(height), int(width)),
            transform=self.transform(),
            invert=True,
            all_touched=all_touched,
)
```

but i'm not sure if this actually removes additional pixels vs just masking them in the arr. @joemcglinchy have you played with this before?

**Comment by lwasser** [comment]
so maybe this is a better option ... to update crop_image to support a rasterio datasetreader OR a numpy array with associated meta.

**Comment by joemcglinchy** [comment]
Thanks for pinging me @lwasser! I agree, we should keep the stack and crop workflows separate. Otherwise we go down the path of overparameterizing (is that a thing?) some of the earthpy functionality. Best to keep it simple and modular.

I had a look at @nkorinek's vignette, and I think it may be able to be changed a bit to use the code as it is currently designed. For instance, starting at line:

```arr, rast = es.stack(stack_bands, out_path=raster, nodata=-9999)
rioobject = rio.open(raster)
boundary = gpd.read_file("data/cold-springs-fire/vector_layers/fire-boundary-geomac/co_cold_springs_20160711_2200_dd83.shp")

 extent = plotting_extent(arr[0], rast["transform"])

 boundary = boundary.to_crs(rast['crs'])

 fig, ax = plt.subplots(figsize=(12, 12))
boundary.plot(ax=ax,color='red', zorder=10)
ep.plot_rgb(arr, ax=ax, stretch=True, extent=extent, str_clip=-.5)
ax.set_title("plswork", fontsize=20)
plt.show()

 crop, meta = es.crop_image(rioobject, boundary)
crop_extent = plotting_extent(crop[0], meta["transform"])
fig, ax = plt.subplots(figsize=(12, 12))
boundary.boundary.plot(ax=ax,color='red', zorder=10)
ep.plot_rgb(crop, ax=ax, stretch=True, extent=crop_extent)
ax.set_title("plswork", fontsize=20)
plt.show() 
``` 

we are opening the DatasetReader object in `riobject`, when we could do the same thing in a `with...` statement:

```
arr, rast = es.stack(stack_bands, out_path=raster, nodata=-9999)
boundary = gpd.read_file("data/cold-springs-fire/vector_layers/fire-boundary-geomac/co_cold_springs_20160711_2200_dd83.shp")

extent = plotting_extent(arr[0], rast["transform"])

boundary = boundary.to_crs(rast['crs'])

fig, ax = plt.subplots(figsize=(12, 12))
boundary.plot(ax=ax,color='red', zorder=10)
ep.plot_rgb(arr, ax=ax, stretch=True, extent=extent, str_clip=-.5)
ax.set_title("plswork", fontsize=20)
plt.show()

# Cropping the stacked image
with rio.open(raster) as rioobject):
    crop, meta = es.crop_image(rioobject, boundary)
    crop_extent = plotting_extent(crop[0], meta["transform"])

fig, ax = plt.subplots(figsize=(12, 12))
boundary.boundary.plot(ax=ax,color='red', zorder=10)
ep.plot_rgb(crop, ax=ax, stretch=True, extent=crop_extent)
ax.set_title("plswork", fontsize=20)
plt.show() 
```

I understand the desire to make `es.crop_image` a little more flexible, though. Providing a numpy array and associated metadata would work as long as the user does the lifting for that upfront.

**Comment by lwasser** [comment]
ok... this is the google doc where the various approaches are discussed!!

https://docs.google.com/document/d/199Z3zyclQQPCVWF4m8-gienT6KViauMveMi9O_wnghM/edit#

**Comment by lwasser** [comment]
https://www.python.org/dev/peps/pep-0020/

CONCLUSION: let's add a list option to `crop_image()` ...

**Comment by lwasser** [comment]
ok closing this -- given we've opened up -- https://github.com/earthlab/earthpy/issues/333  to create a crop function that handles a list of files!!
