### ISSUE TITLE
Migrate documentation to GitHub pages

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthpy#343]
Given the ongoing issues with RTD, we may want to move our docs over to a gh-pages branch (similar to https://github.com/ioos/erddapy). 

This would mean that Travis-CI builds and pushes the documentation to a gh-pages branch. To get this to work, it looks like we'd need to modify the build matrix in `.travis.yml` to add an item for the docs build, then modify the `.travis/test.sh` script to check for a specific job name and build the docs (e.g., https://github.com/ioos/erddapy/blob/master/.travis.yml#L50-L62). 

We could use (doctr)[https://github.com/drdoctr/doctr] to help with deployment to gh-pages (e.g., https://github.com/ioos/erddapy/blob/master/.travis.yml#L64-L66).

**Comment by lwasser** [comment]
thank you @mbjoseph !! this also relates to [this issue here](https://github.com/earthlab/earthpy/issues/337) if we develop this workflow i'll move away from RTD completely and tell him he doensn't have to allocate more resources to us.. Even if he provides the allocation i think we've spent enough time on fixing building docs with RTD even tho they build just fine locally!   :) phew.

**Comment by lwasser** [comment]
@mbjoseph so out of the blue just now both packages docs built successfully via rtd. Why dont we keep this issue open for now but monitor things. If they go down again for a long period of time, let's consider moving to a local build. They must have updated something today. Matplotcheck is working again too.i didnt touch anything to fix docs today.

**Comment by lwasser** [comment]
i am closing this for the time being as RTD has been working lately for us.
