### ISSUE TITLE
Because of rtree, earthpy pip installs on OS X aren't complete

### ISSUE THREAD

**Issue by sgillies** [earthlab/earthpy#432]
**Describe the bug**

Earthpy depends on rtree, which requires libspatialindex, which is not provided by the wheels on PyPI. Until the rtree wheels do include their own requirements, it's on projects like earthpy to explain the dependency.

**Comment by lwasser** [comment]
ahhhhh @sgillies gosh i didn't realize this was an issue. it must be that libspatialindex was installing for us automagically in the dev environment. 

Can you help me understand how you'd like to see this dependency explained? 

i see in the rtree readme

https://pypi.org/project/Rtree/

it just calls it out as a dependency. is that the type of thing that you are looking for here?

Again many thanks for this input!

**Comment by sgillies** [comment]
Yes, I think that would be a good start. But because earthpy is intended to be higher level, for users who aren't necessarily C programmers or sysadmins (like rtree's original audience), some additional documentation may be good. 

Someone who is new to Python and doesn't know what libspatialindex is or where they can get it is in for a hard time when they try to install earthpy from PyPI. Could you make this a conda only package? Is that realistic?

**Comment by lwasser** [comment]
@sgillies do you mean just encourage installation from conda rather than pip? i think that conda is the best way to install given all of the other spatial dependency issues ! you are correct in that we assume our audience are NOT c programmers. we use this package with students who are quite new to programming in general!! 

so documentation could say something like.. we suggest that you install earthpy using conda (conda-forge is our preferred channel) but then given it is on pypi, i could add some language about libspatialindex with a "proceed with caution" stipulation or something?

would that be a reasonable approach?

thank you AGAIN.

**Comment by sgillies** [comment]
@lwasser totally reasonable 👍

**Comment by lwasser** [comment]
ok closing this as well as it was addressed in #440. please reopen if you'd like to see more explanation @sgillies !!
