### ISSUE TITLE
Clarify module descriptions in rst AND delete unused file path checks, context managers, and input type checks in spatial.py

### ISSUE THREAD

**Issue by mgraber** [earthlab/earthpy#67]
## Identify the Documentation Element That You Propose to Update

1) In get-started.rst, the description of the modules as "Spatial IO Utils", is unclear. It looks like it is one module that has utils for input/output of spatial data.
2) Delete commented out lines in spatial.py. The first two are tests that aren't included in the actual function. The third is unused `with` statement.
- https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L123
- https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L164
- https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L173

## Please Identify Your Proposed Changes Below

1) I will change modules description to a bulleted list
2) I will delete the above commented lines, unless the first two checks should be included uncommented.

**Comment by lwasser** [comment]
Hey @mgraber  Thank you for this issue! 
1. If you plan to update the documentation for the modules list, i think it would be helpful to provide a several sentence summary of what each module does in earthpy. So that would required adding some text for both the spatial and io modules.  

2. For the second second set of changes, I would argue that technical ly that code should not be removed, but rather just uncommented if it works properly. It would be ideal to test that that provided destfile path does indeed exist.

```
def stack(sources, dest):
    """Stack a set of bands into a single file.
    Parameters
    ----------
    sources : list of rasterio dataset objects
        A list with paths to the bands you wish to stack. Objects
        will be stacked in the order provided in this list.
    dest : a rio.open writable object that will store raster data.
    """

    #if not os.path.exists(os.path.dirname(dest)):
#    raise ValueError("The output directory path that you provided does not exist")
```

In the code below - https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L164 i would think we would want to test that geoms is a list but it would need to happen in the else statement. I'd really like @mbjoseph on how he thinks we should be testing object structures -- ie could we use duck typing here instead as a list does have methods. i'm just not sure how.
```
 # test that you have a list of a geodataframe
    #if not type(geoms) == list:
    #    raise ValueError("The geoms element used to crop the raster needs to be of type: list. If it is of type dictionary, you can simpy add [object-name-here] to turn it into a list.")

    if type(geoms) == gpd.geodataframe.GeoDataFrame:
        clip_ext = [extent_to_json(geoms)]
    else:
clip_ext = geoms
```
this line:
https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L173

should absolutely be removed. Let's see what max says about the unit testing elements above before moving foward with a pr.

**Comment by mbjoseph** [comment]
Heya @lwasser and @mgraber - my 2 cents is that for the purposes of cleaning up the code, it's a good idea to remove these commented out lines of code. Later, when @lwasser and I write the tests for these functions, she and I can figure out the best approach for ensuring that things to break unexpectedly!

**Comment by mgraber** [comment]
@lwasser and @mbjoseph 

For the first unit test,
```
 #if not os.path.exists(os.path.dirname(dest)):
#    raise ValueError("The output directory path that you provided does not exist")
```
you are already checking to make sure the directory path exists in the `stack_raster_tifs( )` function. So any false path should be caught there before calling `stack( )` from within `stack_raster_tifs()`.

For the second, it looks like the if-else statement accomplishes what the test was trying to do.
```
    # test that you have a list of a geodataframe
    #if not type(geoms) == list:
    #    raise ValueError("The geoms element used to crop the raster needs to be of type: list. If it is of type dictionary, you can simpy add [object-name-here] to turn it into a list.")

    if type(geoms) == gpd.geodataframe.GeoDataFrame:
        clip_ext = [extent_to_json(geoms)]
    else:
        clip_ext = geoms
```

 If the data type given is a geoJSON dictionary, the if statement automatically turns it into a list. Otherwise, it is already a list and isn't modified. The `extent_to_json()` function includes a catch that prints a warning if the input is neither a geoDataFrame or list.

I think both of these make sense to simply delete. Their function is taken care of elsewhere.

**Comment by lwasser** [comment]
well @mgraber  you are totally right if the dir is teste earlier! but i'm not sure i test for a list . the if statement only tests for a geodataframe i think! i had commented it out when i added the functionality for the  function to allow geodataframes! BUT with that said I do like Max's idea as we have some higher level things to discuss AND i totally appreciate your attention to detail @mgraber !!

Please go ahead and submit a PR and i'll create an issue around tests for this function that is totally separate! thank you

**Comment by lwasser** [comment]
Thank you for these changes @mgraber  this issue is now resolved .  it feel free to do so.
