### ISSUE TITLE
(1) Update docstring for cols variable in spatial.py/plot_bands f(x) for spelling and default value and (2) Update formatting of variables in plot_rgb and plot_bands functions.

### ISSUE THREAD

**Issue by yojihigh** [earthlab/earthpy#76]
## Identify the Documentation Element That You Propose to Update
1. [Line 290](https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L290) in spatial.py - fix the spelling error and update to reflect that default is 3 columns if none is specified.
2. Docstrings for plot_rgb and plot_bands have inconsistent formatting of data types for variables and descriptions.

## Please Identify Your Proposed Changes Below
1. Update spelling of "columsn" to "columns", add a default value of 3.
2. Format variables within the docstrings of plot_rgb and plot_bands functions mimicking the rasterio function documentation format as specified.

example change in plot_rgb:
`rgb: list, indices of the three bands to be plotted (default = 0,1,2)`
would be modified to:
`rgb: list (default = 0,1,2)`
`    Indices of the three bands to be plotted`

**Comment by lwasser** [comment]
Hey @yojihigh . thank you for this issue. Just a note that you can link to a line of code like[ this](https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L290):
`https://github.com/earthlab/earthpy/blob/master/earthpy/spatial.py#L290`  this is valuable especially given often the code changes as pull requests are merged

Your issue is a bit unclear. Given there are other people updating docstrings for functions in spatial.py can you kindly specify 2 functions that you'd like to update? if that is what you'd like to do. 

We are asking people to follow the rasterio function documentation format for each function.
[See example here](https://github.com/mapbox/rasterio/blob/master/rasterio/plot.py#L37)

rasterio formats functions as follows
```
"""Display a raster or raster band using matplotlib.
     Text here if needed to describe the function

    Parameters
    ----------
    source : array or dataset object opened in 'r' mode or Band or tuple(dataset, bidx)
        If Band or tuple (dataset, bidx), display the selected band.
        If raster dataset display the rgb image
        as defined in the colorinterp metadata, or default to first band.
    with_bounds : bool (opt)
        Whether to change the image extent to the spatial bounds of the image,
        rather than pixel coordinates. Only works when source is....
```
Please have a look and ping me when you have a more specific update proposal! i just want to avoid merge conflicts on these pull requests.

**Comment by yojihigh** [comment]
@lwasser Updated my proposed changes with additional detail. Please let me know if this makes it clearer!

**Comment by lwasser** [comment]
hey @yojihigh  this is looking very good! please go ahead and submit your PR! please be sure however to UPDATE YOUR FORK first because there have been a lot of changes today! When you submit your PR please ping me for a review. I suggest you try to do this TONIGHT!!

**Comment by yojihigh** [comment]
Pull Request created to resolve this issue
https://github.com/earthlab/earthpy/pull/94

**Comment by lwasser** [comment]
Closing this as the PR was merged. Thank you again @yojihigh
